/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojectlab;

import javax.swing.JOptionPane;

/**
 *
 * @author Raton Biswas
 */
public class Cusromer extends javax.swing.JFrame {

    /**
     * Creates new form Cusromer
     */
    public Cusromer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bn1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bc1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bp1 = new javax.swing.JLabel();
        buy1button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bn2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bc2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bp2 = new javax.swing.JLabel();
        buy2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bn3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bc3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bp3 = new javax.swing.JLabel();
        buy3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        bn4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bc4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        bp4 = new javax.swing.JLabel();
        buy4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        bn5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        bc5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        bp5 = new javax.swing.JLabel();
        buy6 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        bn6 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        bc6 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        bp6 = new javax.swing.JLabel();
        buy7 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("List Of books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 26, 110, 32));

        jLabel2.setText("Book name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, 30));

        bn1.setText("Oporajita");
        getContentPane().add(bn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 79, 63, -1));

        jLabel4.setText("Book code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 69, 61, 34));

        bc1.setText("O-123");
        getContentPane().add(bc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 69, 70, 34));

        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 36, 34));

        bp1.setText("150");
        getContentPane().add(bp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 69, 48, 34));

        buy1button.setText("Buy");
        buy1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy1buttonActionPerformed(evt);
            }
        });
        getContentPane().add(buy1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel8.setText("Book name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 80, 28));

        bn2.setText("Ulysses");
        getContentPane().add(bn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 49, 28));

        jLabel10.setText("Book Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 61, 28));

        bc2.setText("U-123");
        getContentPane().add(bc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 40, -1));

        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        bp2.setText("250");
        getContentPane().add(bp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 28, -1));

        buy2.setText("Buy");
        buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy2ActionPerformed(evt);
            }
        });
        getContentPane().add(buy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel15.setText("Book Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        bn3.setText("Moby Dick");
        getContentPane().add(bn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 160, -1, -1));

        jLabel17.setText("Book Code");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        bc3.setText("M-123");
        getContentPane().add(bc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel19.setText("Price");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        bp3.setText("350");
        getContentPane().add(bp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        buy3.setText("Buy");
        buy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy3ActionPerformed(evt);
            }
        });
        getContentPane().add(buy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel21.setText("Book Name");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        bn4.setText("Hamlet");
        getContentPane().add(bn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel23.setText("Book Code");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        bc4.setText("H-123");
        getContentPane().add(bc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel25.setText("price");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        bp4.setText("450");
        getContentPane().add(bp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        buy4.setText("Buy");
        buy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy4ActionPerformed(evt);
            }
        });
        getContentPane().add(buy4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel27.setText("Book Name");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 244, -1, -1));

        bn5.setText("War and pease");
        getContentPane().add(bn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 244, -1, -1));

        jLabel29.setText("Book Code");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 244, -1, -1));

        bc5.setText("W-123");
        getContentPane().add(bc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 244, -1, -1));

        jLabel31.setText("Price");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 244, -1, -1));

        bp5.setText("550");
        getContentPane().add(bp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 244, -1, -1));

        buy6.setText("Buy");
        buy6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy6ActionPerformed(evt);
            }
        });
        getContentPane().add(buy6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel33.setText("Book Name");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 70, 30));

        bn6.setText("The Ilian");
        getContentPane().add(bn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 50, 30));

        jLabel35.setText("Book Code");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 10));

        bc6.setText("L-123");
        getContentPane().add(bc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 40, 30));

        jLabel37.setText("Price");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, 10));

        bp6.setText("650");
        getContentPane().add(bp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 10));

        buy7.setText("Buy");
        buy7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy7ActionPerformed(evt);
            }
        });
        getContentPane().add(buy7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buy1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy1buttonActionPerformed
         try{
        String name = bn1.getText();
        String code = bc1.getText();
        String price = bp1.getText();
        NewItem i = new NewItem( name,code,price);
        //JOptionPane.showMessageDialog(null, i.showInfo());
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 150;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
            
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
         }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
        
    }//GEN-LAST:event_buy1buttonActionPerformed

    private void buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy2ActionPerformed
        // TODO add your handling code here:
        try{
             String name = bn2.getText();
        String code = bc2.getText();
        String price = bp2.getText();
        NewItem i = new NewItem( name,code,price);
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 250;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
            
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
        }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
    }//GEN-LAST:event_buy2ActionPerformed

    private void buy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy3ActionPerformed
        // TODO add your handling code here:
        try{
             String name = bn3.getText();
        String code = bc3.getText();
        String price = bp3.getText();
        NewItem i = new NewItem( name,code,price);
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 350;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
            
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
        }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
    }//GEN-LAST:event_buy3ActionPerformed

    private void buy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy4ActionPerformed
        // TODO add your handling code here:
        try{
             String name = bn4.getText();
        String code = bc4.getText();
        String price = bp4.getText();
        NewItem i = new NewItem( name,code,price);
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 450;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
            
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
        }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
    }//GEN-LAST:event_buy4ActionPerformed

    private void buy6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy6ActionPerformed
        // TODO add your handling code here:
        try{
             String name = bn5.getText();
        String code = bc5.getText();
        String price = bp5.getText();
        NewItem i = new NewItem( name,code,price);
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 550;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
            
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
            JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
        }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
    }//GEN-LAST:event_buy6ActionPerformed

    private void buy7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy7ActionPerformed
        // TODO add your handling code here:
        try{
             String name = bn6.getText();
        String code = bc6.getText();
        String price = bp6.getText();
        NewItem i = new NewItem( name,code,price);
        String quantity = JOptionPane.showInputDialog("Quantity");
        
        Double totalPrice = (double)Integer.valueOf(quantity) * 650;
          String hora = JOptionPane.showInputDialog("Payment in bikash 10% discount ");
        
        if(hora.equalsIgnoreCase("yes")){
            
            JOptionPane.showMessageDialog(null, "Total Price " + (totalPrice-totalPrice*0.10));
             JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }else{
           
            JOptionPane.showMessageDialog(null, "Total Price " + totalPrice);
             JOptionPane.showMessageDialog(null, "Your item information "+i.showInfo());
            JOptionPane.showMessageDialog(null, "Thank You");
        }
        }catch(Exception ex){
            System.out.println("Exception : "+ex);
        }
     
    }//GEN-LAST:event_buy7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cusromer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cusromer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cusromer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cusromer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cusromer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bc1;
    private javax.swing.JLabel bc2;
    private javax.swing.JLabel bc3;
    private javax.swing.JLabel bc4;
    private javax.swing.JLabel bc5;
    private javax.swing.JLabel bc6;
    private javax.swing.JLabel bn1;
    private javax.swing.JLabel bn2;
    private javax.swing.JLabel bn3;
    private javax.swing.JLabel bn4;
    private javax.swing.JLabel bn5;
    private javax.swing.JLabel bn6;
    private javax.swing.JLabel bp1;
    private javax.swing.JLabel bp2;
    private javax.swing.JLabel bp3;
    private javax.swing.JLabel bp4;
    private javax.swing.JLabel bp5;
    private javax.swing.JLabel bp6;
    private javax.swing.JButton buy1button;
    private javax.swing.JButton buy2;
    private javax.swing.JButton buy3;
    private javax.swing.JButton buy4;
    private javax.swing.JButton buy6;
    private javax.swing.JButton buy7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
